cd /d/Workspaces/Mixed/kebrugs_clash_of_clans/backend

export DB_URL="jdbc:mysql://localhost:3306/clash_of_clans"
export DB_USERNAME="root"
export DB_PASSWORD="root"
export COC_API_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjQ5MGI4ODQwLTkxMTktNDAxMy1hMWYwLTA3NjY0NjQ0N2ZjNCIsImlhdCI6MTc3ODc3OTI5Mywic3ViIjoiZGV2ZWxvcGVyLzkzM2UwN2IwLWMzYmItNWY2Zi1iYjRiLWZmZjYzMzI4NzZkNyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEyMi4xNzIuODcuMjIyIl0sInR5cGUiOiJjbGllbnQifV19._2-IcZoqibC23zum2CpI0DhKSwtICK8mloSuB7SClt86h6v81QTKnft8hSfWVIUYVSd1b_iWUvnwhuTO9a9ffQ"

mvn spring-boot:run
