cd /d/Workspaces/Mixed/kebrugs_clash_of_clans/backend

export DB_URL="jdbc:mysql://localhost:3306/clash_of_clans"
export DB_USERNAME="root"
export DB_PASSWORD="root"
export COC_API_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY0ZjFhZDA4LTM1NTItNDA1OS1iMzI5LTdiNzNhZmM0ZTk4MiIsImlhdCI6MTc3ODQyNDMwNiwic3ViIjoiZGV2ZWxvcGVyLzkzM2UwN2IwLWMzYmItNWY2Zi1iYjRiLWZmZjYzMzI4NzZkNyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE1LjIwNi4yOS4xNiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.vfWuCH_4rovsG9QJhKCf2_Ad5JC4DDmfHCrXTwbsGuZgKXPIMqVTIOzjdckSpWdZ78VTt5NLUYmKtOZSsBUmIg"

mvn spring-boot:run