cd /d/Workspaces/Mixed/kebrugs_clash_of_clans/backend

export DB_URL="jdbc:mysql://localhost:3306/clash_of_clans"
export DB_USERNAME="root"
export DB_PASSWORD="root"
export COC_API_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjU3NDNmM2ExLTJkNjUtNDIyNS1hNzI4LThkM2U5MTVjYWI3OCIsImlhdCI6MTc3MzUwNTU5Nywic3ViIjoiZGV2ZWxvcGVyLzkzM2UwN2IwLWMzYmItNWY2Zi1iYjRiLWZmZjYzMzI4NzZkNyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEyMi4xNzIuODYuMTAxIl0sInR5cGUiOiJjbGllbnQifV19.L9iC344VOq9584B9Fjgoavc_Dj1tqfFvekgECxRF-2yf9ifXpeD6mtikuDmgcSx3vzMHFL3lbk8VXyOBdL6hKQ"

mvn spring-boot:run